# Generated by Django 5.2.6 on 2025-10-01 13:12

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "uf",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "eh_produtor",
                    models.BooleanField(default=False, verbose_name="É produtor"),
                ),
                (
                    "biografia",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Biografia"
                    ),
                ),
                (
                    "contatos",
                    models.TextField(blank=True, null=True, verbose_name="Contatos"),
                ),
                (
                    "links_externos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Links externos"
                    ),
                ),
                (
                    "data_ativacao_produtor",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data ativação produtor"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                (
                    "data_producao",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data de produção"
                    ),
                ),
                ("elenco", models.CharField(max_length=500, verbose_name="Elenco")),
                (
                    "duracao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração (em minutos)"
                    ),
                ),
                (
                    "link_producao",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link da produção"
                    ),
                ),
                (
                    "img_cartaz",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cartazes/",
                        verbose_name="Cartaz",
                    ),
                ),
                (
                    "img_banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        limit_choices_to={"eh_produtor": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.usuario",
                        verbose_name="Produtor",
                    ),
                ),
            ],
        ),
    ]
